### ISSUE TITLE
Are there special care for usage under windows

### ISSUE THREAD

**Issue by intensite** [andresz1/bookshelf-model#1]
Hello Andres,

Are you aware of any special care for usage on windows?
I am new to node.js / bookshelf  and I am experiencing problems with bookshelf-model at the initialization of the models.

I have my models in a subfolder called ../models
From the file models\index.js I have the following code:

``` javascript
var dbConfig = require('../config/database'),
    knex = require('knex')(dbConfig),
    bookshelf = require('bookshelf')(knex),
    bookshelfModel = require('bookshelf-model');


console.log('Current directory: ' + __dirname);
var models = bookshelfModel(bookshelf, __dirname);
app.locals.models = models;
```

**When the code is run, this is what gets outputed:**

 start C:\projets\pci
 node ./bin/www

Current directory: C:\projets\pci\models
C:\projets\pci\node_modules\bookshelf-model\index.js:14
     var model = require(path.join(dir, file))(bookshelf);
                                              ^

TypeError: require(...) is not a function
   at C:\projets\pci\node_modules\bookshelf-model\index.js:14:48
   at Array.forEach (native)
   at module.exports (C:\projets\pci\node_modules\bookshelf-model\index.js:13:6)
   at Object.<anonymous> (C:\projets\pci\models\index.js:12:14)
   at Module._compile (module.js:435:26)
   at Object.Module._extensions..js (module.js:442:10)
   at Module.load (module.js:356:32)
   at Function.Module._load (module.js:311:12)
   at Module.require (module.js:366:17)
   at require (module.js:385:17)
   at Object.<anonymous> (C:\projets\pci\app.js:10:10)
   at Module._compile (module.js:435:26)
   at Object.Module._extensions..js (module.js:442:10)
   at Module.load (module.js:356:32)
   at Function.Module._load (module.js:311:12)
   at Module.require (module.js:366:17)
   at require (module.js:385:17)
   at Object.<anonymous> (C:\projets\pci\bin\www:7:11)
   at Module._compile (module.js:435:26)
   at Object.Module._extensions..js (module.js:442:10)
   at Module.load (module.js:356:32)
   at Function.Module._load (module.js:311:12)

**Could it be related to the path separator in Windows?**

**Comment by intensite** [comment]
Never mind.  The problem was caused by a non model file (index.js) in the models directory.  I needed to have an index.js file in that directory.  Maybe we should have a way to ignore non model files.
